### PR TITLE
elisp: guix-location: Add symbol-at-point check.

### PR DESCRIPTION
**Pull request by wigust**
* elisp/guix-location.el (guix-edit): Add symbol-at-point check.

### CODE REVIEW

**Comment by alezost** [comment]
Hello and thank you for the patch!

IIUC initially you used `symbol-at-point` and then you updated the patch
to use `geiser--symbol-at-point`, right?  Anyway, you call this
`symbol-at-point` function twice, which is not very good.  Besides, it
converts the current thing from a string into a symbol, and then you
convert it back into a string.  I think it would be more clean just to
use the following instead:

```elisp
(or (thing-at-point 'symbol)
    (guix-read-package-name))
```

(requiring `thingatpt` is not needed as `thing-at-point` is autoloaded)

However, there is a problem: what if your point is at some `foobar`
symbol?  After `M-x guix-edit` you will get an error:

    No definitions found for: foobar

What do you think about this problem?

**Comment by alezost** [comment]
Another question: do you think this "symbol at point" thing should work
only for `M-x guix-edit` command or should it work in other places where
package name is read from a user?  For example, in `M-x guix-package-graph`
or `M-x guix-packages-by-name`.

What about adding a user variable `guix-read-package-name-function` that
may be set to any function for reading package names (there may be
`guix-read-package-name-default` and `guix-read-package-name-at-point`
functions for this variable)?  And whenever a user will be prompted for
a package name, the according function will be called.

So the default behaviour will stay as it is now, but you could customize
it like this:

```elisp
(setq guix-read-package-name-function 'guix-read-package-name-at-point)
```

(or you may use your custom function to read the name)

If the above solution is OK for you, I can work on it.

**Comment by wigust** [comment]
Hello Alex,

Alex Kost <notifications@github.com> writes:

> Hello and thank you for the patch!
>
> IIUC initially you used `symbol-at-point` and then you updated the patch
> to use `geiser--symbol-at-point`, right?

Right.  I did this, because `symbol-at-point` handls `,` as a part of
the symbol like `,emacs`.

> Anyway, you call this `symbol-at-point` function twice, which is not
> very good.  Besides, it converts the current thing from a string into
> a symbol, and then you convert it back into a string.  I think it
> would be more clean just to use the following instead:
>
> ```elisp
> (or (thing-at-point 'symbol)
>     (guix-read-package-name))
> ```

Yes, it's more clear and covers case I talked above.

> (requiring `thingatpt` is not needed as `thing-at-point` is autoloaded)
>
> However, there is a problem: what if your point is at some `foobar`
> symbol?  After `M-x guix-edit` you will get an error:
>
>     No definitions found for: foobar
>
> What do you think about this problem?

Hm.  What do you think about adding as a first `or` condition?

`(if current-prefix-arg (guix-read-package-name))`

**Comment by wigust** [comment]
Alex Kost <notifications@github.com> writes:

> Another question: do you think this "symbol at point" thing should work
> only for `M-x guix-edit` command or should it work in other places where
> package name is read from a user?  For example, in `M-x guix-package-graph`
> or `M-x guix-packages-by-name`.

It will definitely be good to have this feature.

> What about adding a user variable `guix-read-package-name-function` that
> may be set to any function for reading package names (there may be
> `guix-read-package-name-default` and `guix-read-package-name-at-point`
> functions for this variable)?  And whenever a user will be prompted for
> a package name, the according function will be called.

Yes, as I see it's a common practice in GNU Emacs.

> So the default behaviour will stay as it is now, but you could customize
> it like this:
>
> ```elisp
> (setq guix-read-package-name-function 'guix-read-package-name-at-point)
> ```
>
> (or you may use your custom function to read the name)
>
> If the above solution is OK for you, I can work on it.

It's a nice solution.  Thank you!

**Comment by alezost** [comment]
Oleg Pykhalov wrote:

> Alex Kost <notifications@github.com> writes:
>
>> IIUC initially you used `symbol-at-point` and then you updated the patch
>> to use `geiser--symbol-at-point`, right?
>
> Right. I did this, because `symbol-at-point` handls `,` as a part of
> the symbol like `,emacs`.

Hm, I don't see how `symbol-at-point` and `geiser--symbol-at-point` can
do different things, as they both just call `(thing-at-point 'symbol)`
and then convert this string into a symbol.

>> What about adding a user variable `guix-read-package-name-function` that
>> may be set to any function for reading package names (there may be
>> `guix-read-package-name-default` and `guix-read-package-name-at-point`
>> functions for this variable)? And whenever a user will be prompted for
>> a package name, the according function will be called.
>
> Yes, as I see it's a common practice in GNU Emacs.

Yeah, there are many `...-function` variables in Emacs used to customize
this or that behavior.  In general, I think the more configurable a
package is, the better.

>> If the above solution is OK for you, I can work on it.
>
> It's a nice solution. Thank you!

Great, I made these changes in commit
31f0efe151b66df2b10e3b78f6915dd9ff85ef10.  Let me know, if anything is
not as you expect.

Oh, as for that potential problem where running `M-x guix-edit` on
`foobar` would lead to an error, I just added a check for a package
name, I mean if symbol at point is a package name, the package will be
opened, and if it is not a package name, a user will prompted for it in
a usual manner.

**Comment by wigust** [comment]
Hello Alex,

Alex Kost <notifications@github.com> writes:

[...]

> Great, I made these changes in commit
> 31f0efe151b66df2b10e3b78f6915dd9ff85ef10.  Let me know, if anything is
> not as you expect.

'C-u xref-find-definitions' allows you to specify symbol even if where
is valid symbol at cursor point.  WDYT about following patch?



Thanks,
Oleg.

**Comment by wigust** [comment]
```diff
diff --git a/elisp/guix-read.el b/elisp/guix-read.el
index 4b350bf..623cd50 100644
--- a/elisp/guix-read.el
+++ b/elisp/guix-read.el
@@ -87,10 +87,13 @@ If it is not a package name, read it from minibuffer."
   (let* ((at-point (thing-at-point 'symbol))
          (name     (and at-point
                         (substring-no-properties at-point))))
-    (if (and name
-             (member name (guix-package-names)))
-        name
-      (guix-read-package-name-default prompt initial-contents))))
+    (cond (current-prefix-arg (guix-read-package-name-default prompt
+                                                              initial-contents))
+          ((and name
+                (member name (guix-package-names)))
+           name)
+          (t (guix-read-package-name-default prompt
+                                             initial-contents)))))
 
 (defun guix-read-package-name (&optional prompt initial-contents)
   "Read a package name using `guix-read-package-name-function'."
```

**Comment by alezost** [comment]
Committed as ab978621673bcc74242fa0ec84371deca57d8eb5, thank you!

I moved the check for `current-prefix-arg` to the beginning, since there
is no need to find symbol at point, if current-prefix-arg is specified.

**Comment by wigust** [comment]
Thank you!

I close the pull request.

**Pull request closed without merging**
